import React from "react";

export const TableData = [
  {
    platform: "Платформа не указана",
    maker: "CISCO",
    divices: 30,
    divicesActive: 11,
    activeNotInUse: 14,
    noActive: 3,
  },
  {
    platform: "А",
    maker: "AAAAA",
    divices: 12,
    divicesActive: 2,
    activeNotInUse: 13,
    noActive: 55,
  },
  {
    platform: "Б",
    maker: "BBBBA",
    divices: 22,
    divicesActive: 62,
    activeNotInUse: 543,
    noActive: 5,
  },
  {
    platform: "В",
    maker: "ASDAS",
    divices: 248,
    divicesActive: 46,
    activeNotInUse: 83,
    noActive: 514,
  },
  {
    platform: "Г",
    maker: "GGG",
    divices: 2,
    divicesActive: 2,
    activeNotInUse: 165,
    noActive: 512,
  },
  {
    platform: "Д",
    maker: "GFFF",
    divices: 2,
    divicesActive: 2,
    activeNotInUse: 3,
    noActive: 5,
  },
  {
    platform: "Ж",
    maker: "KKKK",
    divices: 2,
    divicesActive: 2,
    activeNotInUse: 3,
    noActive: 5,
  },
  {
    platform: "А",
    maker: "AAAAA",
    divices: 12,
    divicesActive: 2,
    activeNotInUse: 13,
    noActive: 55,
  },
  {
    platform: "Б",
    maker: "BBBBA",
    divices: 22,
    divicesActive: 62,
    activeNotInUse: 543,
    noActive: 5,
  },
  {
    platform: "В",
    maker: "ASDAS",
    divices: 248,
    divicesActive: 46,
    activeNotInUse: 83,
    noActive: 514,
  },
];
